name: Codex Guard

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run format:check

      - name: ESLint
        run: npm run lint

      - name: Stylelint
        run: npm run stylelint

      - name: Tokens up-to-date
        run: npm run guard:tokens:check

      - name: Accessibility (Axe)
        run: npx axe --tags wcag2a,wcag2aa --exit 1 index.html
